language: python
python:
  - "3.6.4"

cache: pip

install:
  - pip install -r requirements.txt

before_script:
  - pip --version
  - pip freeze

script:
  - flake8 --exclude demo,templates  --max-line-length 80
  - coverage run -m unittest

after_success:
  - codecov

