language: python
python:
  - "3.6.4"

install:
  - pip install -r requirements.txt

before_script:
  - pip --version
  - pip freeze

script:
  - flake8 --exclude demo
  - coverage run -m unittest

after_success:
  - codecov

